### PR TITLE
Add ruby-3.3 advisories seeded from ruby 3.2.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by dlorenc** [comment]
Ref https://github.com/wolfi-dev/os/pull/4855/

**Review by pdeslaur — APPROVED** [review]

**Comment by luhring** [comment]
🤔  We probably want to use current timestamps here — they're intended to capture when we became aware of each event for each advisory (for each package). Let me know if I'm missing something about this situation

**Comment by pdeslaur** [comment]
> 🤔 We probably want to use current timestamps here — they're intended to capture when we became aware of each event for each advisory (for each package). Let me know if I'm missing something about this situation

True - I didn't think about that, but I agree.

**Comment by luhring** [comment]
I just built and scanned `ruby-3.3` to see what was coming up:

```console
$ w scan packages/aarch64/ruby-3.3-dev-3.3.0_p1-r3.apk
Will process: ruby-3.3-dev-3.3.0_p1-r3.apk
✅ No vulnerabilities found
```

I'll close this one for now but we can revisit/redo it if needed!

**Pull request closed without merging**
