### PR TITLE
chore: remove cluster-autoscaler advisory files

### PR DESCRIPTION
**Pull request by hectorj2f**
These packages have been moved to enterprise-packages.

### CODE REVIEW

**Comment by cpanato** [comment]
need rebase

**Comment by hectorj2f** [comment]
Done

**Comment by cpanato** [comment]
Were the packages withdrawn as well? otherwise, i think we keep those here

thoughts @luhring ?

**Comment by luhring** [comment]
> Were the packages withdrawn as well? otherwise, i think we keep those here
> 
> thoughts @luhring ?

I think this kind of cleaning up is the right move. If the package is no longer maintained in Wolfi, and specifically if it's been moved to another package repo like enterprise, let's make sure the enterprise advisory data has what it needs and then remove it from Wolfi advisory data.

This helps us move toward a "clean" state where there's no duplication of a package's advisory data across the repos. And soon I'm hoping we'll consolidate to a single git repo.

Thanks @hectorj2f!

**Comment by hectorj2f** [comment]
Everything is clean and ready for removal of these advisory files.

**Review by luhring — APPROVED** [review]

**Comment by cpanato** [comment]
good to know

**Pull request merged**
