### PR TITLE
mattermost-9: update advisory

### PR DESCRIPTION
**Pull request by Dentrax**

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]

**Comment by hectorj2f** [comment]
@Dentrax It seems we removed some CVEs.

**Review by hectorj2f — CHANGES_REQUESTED** [review]
Restore all the removed CVEs.

**Comment by luhring** [comment]
@Dentrax I'm wondering if you tried to overwrite the existing file here in Wolfi advisories altogether. If so, know that _we can't do that_, since that's going to delete advisories we've already started.

It sounds like what we mean to do here is to just add the conclusion events (like false positives, and pending upstream fix) from the extra advisories to this file. That will have to be done by hand for now (this seems like a one-off accident scenario, based on the context I'm seeing in Slack).

Once that's done, I'm expecting we'll remove the package from extra packages and the advisories file from extra advisories. Let me know if I'm mistaken here!!

**Comment by hectorj2f** [comment]
It seems there aren't any changes.

**Comment by hectorj2f** [comment]
@Dentrax This LGTM, I am gonna use this PR for some testing if you don't mind. I will take care of it.

**Review by hectorj2f — APPROVED** [review]

**Pull request merged**
